# .github/workflows/trigger-workflow.yml in clientRepo
name: Base Workflow

on:
  workflow_dispatch:

jobs:
 call-workflow:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Call Trigger workflow
      uses: ./.github/workflows/Trigger-workflow.yml
      with:
       message: “Triggered Flow”
