name: Create Dev Test and Prod Environments
# clean up the environment for the next demo
#  clean up environment tasks for QA and Prod 

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ feature1 ]
    inputs:
    
     env_name:
     description: name for the environment to be created
     required: true
     default: PracTest
     
     client_id:
     description: service principal client id
     required: true
     default: 6d8e8818-1b71-416b-8ce9-2ff19aed6445
     
     user_id:
     description: AAD object id for the user
     required: true 
     default: 687e7560-7f7e-4ca8-b0c3-a9edeb46e97f
   
 #Do Not change these values
      

jobs:
  Create-Environments:
    runs-on: ubuntu-latest
    # or you can say runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Create Developer Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        name: ${{ github.event.inputs.env_name}}
        type: Sandbox
        domain: ${{ github.event.inputs.env_name}}
    
    - name: assign-user to developer environment
      uses:  microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        environment: 'https://${{ github.event.inputs.env_name}}.crm8.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator
        
