name: Create Dev Test and Prod Environments
# clean up the environment for the next demo
#  clean up environment tasks for QA and Prod 

'on':
  - push
 #Do Not change these values
      

jobs:
  Create-Environments:
    runs-on: ubuntu-latest
    # or you can say runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Create Developer Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN}}
        tenant-id: ${{secrets.TENANT_ID}}
        name: PracTest1
        type: Developer
        domain: PracTest1
    
    - name: assign-user to developer environment
      uses:  microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN}}
        tenant-id: ${{secrets.TENANT_ID}}
        environment: 'https://PracTest1.dynamics.com'
        user: ${{ secrets.user_id}}
        role: System Administrator
        
    
