name: export-and-branch-solution

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"   
      
    # - name: Install PAC
    #   uses: ./actions-install
    #   id: actions-install

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    # - name: who-am-i action
    #   uses: microsoft/powerplatform-actions/who-am-i@v0
    #   with:
    #     environment-url: 'https://orgfc38be7b.crm8.dynamics.com/'
    #     app-id: ${{ vars.CLIENT_ID }}
    #     client-secret: ${{ secrets.PowerPlatformSPN1 }}
    #     tenant-id: ${{ vars.TENANT_ID }}
        
    - name: export-solution-Managed action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://orgfc38be7b.crm8.dynamics.com/'
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN1 }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name: ALMTest1
        solution-output-file: ${{ github.event.repository.name }}/Artifacts/${{ steps.date.outputs.date }}/Managed/ALMLab.zip
        overwrite: true
        managed: true

    - name: unpack-solution-Managed action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.repository.name }}/Artifacts/${{ steps.date.outputs.date }}/Managed/ALMLab.zip
        solution-folder: ${{ github.event.repository.name }}/Artifacts/${{ steps.date.outputs.date }}/Managed/ALMLab
        solution-type: 'Managed'
        overwrite-files: true
        
    - name: export-solution-Unmanaged action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://orgfc38be7b.crm8.dynamics.com/'
        app-id: ${{ vars.CLIENT_ID }}
        client-secret: ${{ secrets.PowerPlatformSPN1 }}
        tenant-id: ${{ vars.TENANT_ID }}
        solution-name: ALMTest1
        solution-output-file: ${{ github.event.repository.name }}/Artifacts/${{ steps.date.outputs.date }}/Unmanaged/ALMLab.zip
        overwrite: true
        managed: false

    - name: unpack-solution-Unmanaged action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.repository.name }}/Artifacts/${{ steps.date.outputs.date }}/Unmanaged/ALMLab.zip
        solution-folder: ${{ github.event.repository.name }}/Artifacts/${{ steps.date.outputs.date }}/Unmanaged/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true
        

    - name: Git Fetch and Commit 
      run: |
        git fetch --all  
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates from the Golden Source environment"
        git remote set-url origin https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ github.repository }}
        git push
        
    # - name: Prepare solution changes for check-in into source control
    #   uses: microsoft/powerplatform-actions/branch-solution@v1
    #   with:
    #     solution-folder: ${{ github.event.repository.name }}/Artifacts/ALMLab
    #     solution-target-folder: ${{ github.event.repository.name }}/Artifacts/ALMLab1
    #     token: ${{ secrets.REPOCHECKINTOKEN }}
    #     allow-empty-commit: true
