    - name: Install JFrog
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://sample.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.MSDE_ARTIFACTORY_TOKEN }}
        with:
          version: 2.25.2
          download-repository: jfrog-cli-external
