# .github/workflows/trigger-workflow.yml in clientRepo
name: Jfrog

on:
  workflow_dispatch:

jobs:
 call-workflow:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - uses: jfrog/setup-jfrog-cli@v4
      env:
       JF_URL: ${{ vars.JF_URL }}
       JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }} 


       
    - name: Install JFrog
      uses: jfrog/setup-jfrog-cli@v3
      env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_PROJECT }}
    - run: |
         jf rt ping    
    
    # - name: Push Build to Artifactory
    #   run: |
    #    echo "test file " > test.txt
    #    export BUILD_NAME="my-build"
    #    export BUILD_MODULE="my-module"
    #    export BUILD_NUMBER="1"

    #    export PATH_TO_DIRECTORY="name/version/dates"
      
    #    jf rt upload "test.txt" ALMPowerAppsDemo/$PATH_TO_DIRECTORY --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE
