# .github/workflows/trigger-workflow.yml in clientRepo
name: Jfrog

on:
  workflow_dispatch:

jobs:
 call-workflow:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    
    - name: Install JFrog
      uses: jfrog/setup-jfrog-cli@v3
      env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_PROJECT }}
      with:
          version: 2.25.2
          download-repository: jfrog-cli-external
