name: Release-From-Build

on:
 workflow_dispatch:     
    inputs:
      solutions: 
        description: 'Comma-separated list of solutions to export'
        default: 'ALMTest1 ALMTest2 ALMTest3'
      run_no:
        description: 'Build no. of the artifacts uploaded in the repository'
        required: true
        
jobs:
 init:
    runs-on: ubuntu-latest
    outputs:
      solutions: ${{ steps.generate-matrix.outputs.solutions}}
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          solutions=$(echo '"${{ github.event.inputs.solutions }}"' | jq -c '. | split(" ") | map(select(length > 0))')
          echo "solutions=$solutions" >> $GITHUB_OUTPUT
          
 Deploy-SIT1:
    needs: init
    #needs: [defineBuilds, build]
    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        solution: ${{ fromJSON(needs.init.outputs.solutions)}}
    environment:
      name: Test
      url: https://orgbf941a56.crm.dynamics.com/

    steps:
      - name: build
        run: |
          echo "Solution: ${{ matrix.solution }}"
      - name: Checkout repository
        uses: actions/checkout@v4
              
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Export solution as managed
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: 'https://orgfc38be7b.crm8.dynamics.com/'
          app-id: ${{ vars.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN1 }}
          tenant-id: ${{ vars.TENANT_ID }}
          solution-name: ${{ matrix.solution }}
          solution-output-file: /out/Export/${{ matrix.solution}}.zip
          overwrite: true
          managed: true
                 
 #      - name: Import solution - ${{ matrix.solution }}
 #        uses: microsoft/powerplatform-actions/import-solution@v1
 #        with:
 #          environment-url: ${{ vars.SIT1_URL }}
 #          app-id: ${{ vars.QA_SPN_APP_ID }}
 #          client-secret: ${{ secrets.QA_SPN_SECRET }}
 #          tenant-id: ${{ vars.Build_Tenant_ID }}
 #          solution-file: "Artifacts/12/${{ matrix.solution }}/Managed/${{ matrix.solution }}.zip"
 #          force-overwrite: true
 #          publish-changes: true
 #          run-asynchronously: true
 #          max-async-wait-time: 90
 #          skip-dependency-check: true
 
    # Environment protection rule for SIT1 approval
    env:
      required: true
