name: Triggered Workflow
on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Print Message
      # run: echo “${{ inputs.message }}”
      run: echo “${{ "Hello" }}”
